In [ ]:
# 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:
import numpy as np
# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
matrix = np.zeros((2,2))
print("Initialized an empty array with size 2X2. \n",matrix)
# 2. Initialize an all one array with size 4X2.
matrix1 = np.ones((4,2))
print("Initialized an all one array with size 4X2. \n",matrix1)
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr = np.full((2,2),5) #5 is the fill
print(" Returned new array of given shape and type, filled with fill value. \n",arr)
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = np.array([[1,2],
              [3,4]])
b = np.zeros_like(a)
print("Returned a new array of zeros with same shape and type as a given array. \n",b)
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
a1=np.array([[1,2],
            [3,4]])
b1=np.ones_like(a1)
print("Returned new array of ones with same shape and type as a given array. \n",b1)
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list=[1,2,3,4]
b2=np.array(new_list)
print("Converted numpy array. \n",b2)



Initialized an empty array with size 2X2. 
 [[0. 0.]
 [0. 0.]]
Initialized an all one array with size 4X2. 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
 Returned new array of given shape and type, filled with fill value. 
 [[5 5]
 [5 5]]
Returned a new array of zeros with same shape and type as a given array. 
 [[0 0]
 [0 0]]
Returned new array of ones with same shape and type as a given array. 
 [[1 1]
 [1 1]]
Converted numpy array. 
 [1 2 3 4]


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
a = np.arange(10,49)
print("An array with values ranging from 10 to 49 \n",a)
# 2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
b=np.arange(9).reshape(3,3)
print("A 3X3 matrix with values ranging from 0 to 8 \n",b)
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
c=np.eye(3,3)
print("A 3X3 identity matrix \n",c)
# 4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
d = np.random.random(30)
e = np.mean(d)
print("A random array of size 30 and find the mean of the array \n",e)
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
f = np.random.random((10,10))
g = f.min()
h = f.max()

print("A 10X10 array with random values and find the minimum and maximum values \n",g,h)
# 6. Create a zero array of size 10 and replace 5th element with 1.
i = np
j = np.zeros(10)
j[4] = 1
print("A zero array of size 10 and replace 5th element with 1 \n",j)

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
k = arr[::-1]
print("Reverse an array arr = [1,2,0,0,4,0] \n",k)

# 8. Create a 2d array with 1 on border and 0 inside.
l = np.ones((5,5))
l[1:-1,1:-1] = 0
print("A 2d array with 1 on border and 0 inside \n",l)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

m = np.zeros((8,8))
m[1::2, ::2] =1 # rows 1,3,5,7 --> columns 0,2,4,6
m[::2, 1::2] =1 #rows 0,2,4,6 --> 1,3,5,7
print("A 8X8 matrix and fill it with a checkerboard pattern \n",m)



An array with values ranging from 10 to 49 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
A 3X3 matrix with values ranging from 0 to 8 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A 3X3 identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A random array of size 30 and find the mean of the array 
 0.5520079395241937
A 10X10 array with random values and find the minimum and maximum values 
 0.01967304294864458 0.993307781437993
A zero array of size 10 and replace 5th element with 1 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reverse an array arr = [1,2,0,0,4,0] 
 [0 4 0 0 2 1]
A 2d array with 1 on border and 0 inside 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
A 8X8 matrix and fill it with a checkerboard pattern 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0

In [ ]:

# Problem - 3: Array Operations:
import numpy as np
# For the following arrays:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
# Complete all the task using numpy:
# 1. Add the two array.

add = np.add(x, y)
print("Addition:\n", add)
# 2. Subtract the two array.
sub = np.subtract(x, y)
print("Subtraction:\n", sub)
# 3. Multiply the array with any integers of your choice.
mul = np.multiply(x, y)
print("Multiplication:\n", mul)
# 4. Find the square of each element of the array.
sq = np.square(x)
print("Square:\n", sq)
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)


# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.

concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along row:\n", concat_xy_row)

concat_vw_col = np.concatenate((v, w), axis=0)
print("Concatenate v and w along column:\n", concat_vw_col)

# {Hint:try np.concatenate() or np.vstack() functions.
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error caused while concatenating x and v because ", e)


Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplication:
 [[ 5 12]
 [21 40]]
Square:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [ 9 10 11 12]
Error caused while concatenating x and v because  all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:

import numpy as np

# Problem - 4: Matrix Operations:
# • For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
# print("A · A^-1 =\n", I) (This will not give the exact rounded value)
print("Rounded A · A^-1 =\n\n", np.round(I, 5))

# 2. Prove AB != BA.

AB = np.dot(A, B)
BA = np.dot(B, A)
print("A·B =\n \n", AB)
print("B·A =\n \n", BA)
print("AB == BA : ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T · A^T
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T =\n \n", AB_T)
print("B^T·A^T =\n \n", BT_AT)
print("(AB)^T == B^T·A^T : ", np.array_equal(AB_T, BT_AT))

# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9


# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

# Solve using inverse
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("Solution [x, y, z] =", X)

# • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve  [x, y, z] =", X_solve)


Rounded A · A^-1 =

 [[1. 0.]
 [0. 1.]]
A·B =
 
 [[23 13]
 [51 29]]
B·A =
 
 [[36 44]
 [13 16]]
AB == BA :  False
(AB)^T =
 
 [[23 51]
 [13 29]]
B^T·A^T =
 
 [[23 51]
 [13 29]]
(AB)^T == B^T·A^T :  True
Solution [x, y, z] = [ 2.  1. -2.]
Solution using np.linalg.solve  [x, y, z] = [ 2.  1. -2.]
